# Generated by Django 5.1 on 2024-09-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('supplements_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplements', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
